### ISSUE TITLE
Decks are not detected after saving them and tracker process isn't killed when exiting the program

### ISSUE THREAD

**Issue by hhu94** [shawkinsl/mtga-tracker#97]
[output_log.txt](https://github.com/shawkinsl/mtga-tracker/files/1874042/output_log.txt)

I did not find any log file named mtga_watch.log in my MTGATracker install directory

[mtga-tracker.zip](https://github.com/shawkinsl/mtga-tracker/files/1874043/mtga-tracker.zip)

The program doesn't detect my decks even after opening them and clicking on Done. I've done this with both MTGA and the program open, I've tried opening MTGA first and the tracker first, neither method works.

Also, when I close the tracker (right click -> Close), the process is not killed and can only be killed through the Task Manager.

**Comment by shawkinsl** [comment]
Hi hhu94. Thanks for the report, and sorry you're running into issues! Could you let me know a little more about your system? What version of windows are you running, is it 64 bit, etc.

It will also be helpful to see console output when running the executable from the command line. I am guessing there is a crash happening, but the UI isn't being notified. Here's a quick example of how you could get this info with cmd.exe: http://recordit.co/342hTkXpGG

If there's any way you could use software like OBS or recordit to record video of attempting these steps, that would be even better.

**Comment by shawkinsl** [comment]
Also, you're totally right, parting to `%APPDATA%` info windows explorer won't get you to the right place, sorry about that! The full path is actually `C:\Users\YourUsername\AppData\LocalLow\MTGATracker` (or,. %APPDATA, up one level, then down into LocalLow). Sorry about the confusion!

**Comment by hhu94** [comment]
```
C:\Program Files\MTGATracker-win32-x64_1.0.0-beta>MTGATracker.exe

C:\Program Files\MTGATracker-win32-x64_1.0.0-beta>
child process success on port 8089
err: [7676] Failed to execute script mtgatracker_backend

err: Traceback (most recent call last):
  File "app\mtgatracker_backend.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\spencatro\pycharmprojects\mtga-tools\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "app\tasks.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\spencatro\pycharmprojects\mtga-tools\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "app\dispatchers.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\spencatro\pycharmprojects\mtga-tools\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "app\parsers.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\spencatro\pycharmprojects\mtga-tools\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "app\models\game.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\spencatro\pycharmprojects\mtga-tools\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "app\mtga_app.py", line 18, in <module>
  File "logging\handlers.py", line 150, in __init__
  File "logging\handlers.py", line 57, in __init__
  File "logging\__init__.py", line 1030, in __init__
  File "logging\__init__.py", line 1059, in _open
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\MTGATracker-win32-x64_1.0.0-beta\\mtga_watch.log'

python exited with code 4294967295
(node:9956) Warning: No such label 'init' for console.timeEnd()
```

It looks like there is a PermissionError. I think it's probably because I placed the folder in `C:\Program Files`.

I'll try putting it somewhere else and report back.

Also, my windows is 64 bit.

**Comment by hhu94** [comment]
I can confirm both problems are gone after moving the install directory to my Desktop. You can close this issue now but I'd suggest implementing a popup for any errors encountered so that all errors are visible to the user.

**Comment by kealdor** [comment]
Duplicate of #485 
Duplicate of #514
